### PR TITLE
fix broken links to python and java endpoints doc

### PR DESCRIPTION
**Pull request by jittuu**

### CODE REVIEW

**Comment by campoy** [comment]
Due to an error on the travis.yml your PR is failing the tests. Could you pull from upstream and retry?

Thanks
Francesc

**Comment by dhermes** [comment]
@campoy You know you can accept the PR without tests failing. There is literally 0 chance that updating links in a README will cause Travis to fail. The diff will be applied cleanly, the end :smile:

**Comment by campoy** [comment]
My goal was to get @jittuu to get a message asking him to sign the CLA.

But I can also ask it directly:

@jittuu, could you please sign this CLA https://cla.developers.google.com/

Thanks

**Comment by dhermes** [comment]
Fancy :grin:

**Comment by jittuu** [comment]
@campoy signed! :)

**Pull request merged**
