### PR TITLE
Doc : update on the new context.Context

### PR DESCRIPTION
**Pull request by ritoon**
After the new usage for context.Context some samples where still with endpoints.Context

### CODE REVIEW

**Comment by odeke-em** [comment]
Luckily doc.go is already updated to use context.Context as per https://github.com/GoogleCloudPlatform/go-endpoints/blob/master/endpoints/doc.go

@ritoon perhaps can we retitle this PR to
```
README: use context.Context instead of endpoint.Context in examples
```
as well as change the commit message if possible?

**Comment by adams-sarah** [comment]
@odeke-em thanks for resurrecting this!
@ritoon LGTM, except commit message should be like @odeke-em suggests.
I will merge and update message myself.

Thanks!

**Comment by odeke-em** [comment]
Cheers @adams-sarah, and thanks @ritoon for the PR!

**Pull request merged**
