### PR TITLE
oauth: Remove references to internal packages

### PR DESCRIPTION
**Pull request by flowlo**
Fixes GoogleCloudPlatform/go-endpoints#101

### CODE REVIEW

**Comment by campoy** [comment]
Hey @crhym3, do you think this is correct?

Looks good to me, but I'm not an expert on the intricacies of oauth2.

**Comment by campoy** [comment]
Hey @crhym3, do you think this is correct?

Looks good to me, but I'm not an expert on the intricacies of oauth2.

**Comment by broady** [comment]
This looks reasonable to me.

**Comment by campoy** [comment]
Thanks @broady, I wonder why we used the proto directly on the previous code. Do you know?

I'll wait for @crhym3 to give some context and merge then.

**Comment by crhym3** [comment]
LGTM
Thanks for fixing this.

IIRC we used proto because `User.ClientID` or some other field wasn't available at the time.

**Comment by flowlo** [comment]
Woah, that came as a surprise after half a year, cool! :open_mouth: @crhym3 you're welcome :smile:

**Comment by broady** [comment]
Checked and verified that @flowlo has signed the Google CLA.

**Pull request merged**
